### ISSUE TITLE
Abnormal situation when using Spock

### ISSUE THREAD

**Issue by lovehxl** [pgEdge/spock#10]
Hello, I am directly using Spock for data mutual subscription and want to achieve data synchronization between multiple nodes. Currently, there is no problem with data synchronization between two nodes, but when synchronizing data between three nodes, one node may illegally synchronize the other two nodes. In addition, when using update, multiple queries may result in data before modification. Can you provide some suggestions? Thank you！

**Comment by luss** [comment]
We'll need more details in order to help you figure this out together.
what do you mean by "*one node may illegally synchronize the other two *
*nodes*"?

Also, I do not understand what "*when using update, multiple queries may
result in data before modification*" means.

**Comment by lovehxl** [comment]
Okay, let me now go through the detailed steps:

1.Firstly, I prepared three servers to compile and install PG16 and Spock. The IP addresses of the three servers are  {192.168.10.52/188/189}


2.After installing Spock, create a provider node, and create a provider node for all three nodes:
SELECT spock.node_create(
    node_name := 'fb52',
    dsn := 'host=192.168.10.52 port=5435 dbname=postgres user=postgres password=bbibm001'
);
SELECT spock.node_create(
    node_name := 'fb188',
    dsn := 'host=192.168.10.188 port=5435 dbname=postgres user=postgres password=bbibm001'
);
SELECT spock.node_create(
    node_name := 'fb189',
    dsn := 'host=192.168.10.189 port=5435 dbname=postgres user=postgres password=bbibm001'
);


3.Subsequently, subscribe to each other among the three servers, namely 52 subscriptions 188 and 189; 188 subscription 52 and 189; 189 Subscriptions 52 and 188
52node：
SELECT spock.sub_create(
    subscription_name := 'dy188',
    provider_dsn := 'host=192.168.10.188 port=5435 dbname=postgres user=postgres password=bbibm001'
);
SELECT spock.sub_create(
    subscription_name := 'dy189',
    provider_dsn := 'host=192.168.10.189 port=5435 dbname=postgres user=postgres password=bbibm001'
);


188node：
SELECT spock.sub_create(
    subscription_name := 'dy52',
    provider_dsn := 'host=192.168.10.52 port=5435 dbname=postgres user=postgres password=bbibm001'
);
SELECT spock.sub_create(
    subscription_name := 'dy189',
    provider_dsn := 'host=192.168.10.189 port=5435 dbname=postgres user=postgres password=bbibm001'
);


189node：
SELECT spock.sub_create(
    subscription_name := 'dy52',
    provider_dsn := 'host=192.168.10.52 port=5435 dbname=postgres user=postgres password=bbibm001'
);
SELECT spock.sub_create(
    subscription_name := 'dy188',
    provider_dsn := 'host=192.168.10.188 port=5435 dbname=postgres user=postgres password=bbibm001'
);


4.Create table test, create table test1 together on all nodes
CREATE TABLE test1 (
 ID UUID DEFAULT gen_random_uuid ( ) PRIMARY KEY,
 a1 VARCHAR ( 200 ),
 a2 VARCHAR ( 200 ),
 a3 VARCHAR ( 200 ),
 a4 VARCHAR ( 200 ),
 a5 VARCHAR ( 200 ),
 a6 VARCHAR ( 200 ),
 a7 VARCHAR ( 200 ),
 a8 VARCHAR ( 200 ),
 a9 VARCHAR ( 200 ),
 a10 VARCHAR ( 200 ),
 a11 VARCHAR ( 200 ),
 a12 VARCHAR ( 200 ),
 a13 VARCHAR ( 200 ),
 a14 VARCHAR ( 200 ),
 a15 VARCHAR ( 200 ),
 a16 VARCHAR ( 200 ),
 a17 VARCHAR ( 200 ),
 a18 VARCHAR ( 200 ),
 a19 VARCHAR ( 200 ),
 a20 VARCHAR ( 200 ) 
);


5.Add the table to the default replication set, and perform this operation on all nodes
SELECT spock.repset_add_all_tables('default', ARRAY['public']);


6.Create an insert data function for data insertion testing, Perform this operation on all three nodes
CREATE 
 OR REPLACE FUNCTION my_produce_function1 ( total INT ) RETURNS void AS $$ DECLARE
 i INTEGER := 0;
BEGIN
  WHILE
  i < total
  LOOP
  INSERT INTO test1 (a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20)
 VALUES
  ('a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18','a19','a20');
 i := i + 1;
END LOOP;
END;
$$ LANGUAGE plpgsql;


7.Execute data insertion function to view data synchronization results
Insert on 52 node：select my_produce_function1(10);
Insert on 188 node：select my_produce_function1(20);
Insert on 189 node：select my_produce_function1(30);


Result:
Count data on 52: 60
Count data on 188: 20
Count data on 189: 60 


Here, it can be seen that 52 and 189 had already subscribed to each other when inserting data, and the data synchronization was successful. However, 188 did not synchronize the data inserted by 52 and 189, and both 188 and 189 were synchronized.


8.Delete Test
Delete 5 pieces of data on 188:
Result:
Count data on 52: 55
Count data on 188: 15
Count data on 189: 55


Delete 5 pieces of data on 189:
Result:
Count data on 52: 50
Count data on 188: 15
Count data on 189: 50


Delete 5 pieces of data on 52:
Result:
Count data on 52: 45
Count data on 188: 15
Count data on 189: 45


Here, it can be seen that 188 did not synchronize the deletion of data on 52 and 189. When deleting on 188, 52 and 189 performed the deletion operation.


9.Modify Test
Execute the modification statement on node 52 and modify the a1 field to "a1-updata".
UPDATE test1 set a1 = 'a1-update';




Result:
The results obtained from multiple queries are different, with some data modified successfully and some failed; There may also be two situations when the same data is queried multiple times. The following two figures:






10. In summary
I am currently facing two issues
(1) The problem of incomplete synchronization of data due to over 2 mutual subscriptions among nodes
(2) After data modification, there is a certain probability that the query data will reveal the data before modification


Can you help me see where the problem is and give me some feedback? Thank you very much




---- Repli
ed Message ----
| From | Denis ***@***.***> |
| Date | 9/22/2023 19:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [pgEdge/spock] Abnormal situation when using Spock (Issue #10) |

We'll need more details in order to help you figure this out together.
what do you mean by "*one node may illegally synchronize the other two *
*nodes*"?

Also, I do not understand what "*when using update, multiple queries may
result in data before modification*" means.

**Comment by lovehxl** [comment]
Do you understand what I'm saying


| |
绿萝蔓蔓绕枝生
|
|
***@***.***
|
---- Replied Message ----
| From | Denis ***@***.***> |
| Date | 9/22/2023 19:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [pgEdge/spock] Abnormal situation when using Spock (Issue #10) |

We'll need more details in order to help you figure this out together.
what do you mean by "*one node may illegally synchronize the other two *
*nodes*"?

Also, I do not understand what "*when using update, multiple queries may
result in data before modification*" means.

**Comment by nkev** [comment]
@luss  I'm wondering why this issue is closed without a reply? @lovehxl gave you step-by-step instructions on how to reproduce the issue. Others (like me) are also keen to see your response.

**Comment by lovehxl** [comment]
There is no such problem now







| |
绿萝蔓蔓绕枝生
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/31/2024 07:15 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [pgEdge/spock] Abnormal situation when using Spock (Issue #10) |

@luss I'm wondering why this issue is closed without a reply? @lovehxl gave you step-by-step instructions on how to reproduce the issue. Others (like me) are also keen to see your response.

**Comment by nkev** [comment]
@lovehxl Were the issues fixed with an update to Spock or was it user error?

**Comment by lovehxl** [comment]
Spock's update has resolved the issue







| |
绿萝蔓蔓绕枝生
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/19/2024 12:12 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [pgEdge/spock] Abnormal situation when using Spock (Issue #10) |

@lovehxl Were the issues fixed with an update to Spock or was it user error?

**Comment by lovehxl** [comment]
I would like to know if it is possible to create a table on one of the nodes after setting up the cluster, and synchronize it with the other nodes







| |
绿萝蔓蔓绕枝生
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/20/2024 09:40 |
| To | ***@***.***> |
| Subject | Re: [pgEdge/spock] Abnormal situation when using Spock (Issue #10) |
Spock's update has resolved the issue







| |
绿萝蔓蔓绕枝生
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/19/2024 12:12 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [pgEdge/spock] Abnormal situation when using Spock (Issue #10) |

@lovehxl Were the issues fixed with an update to Spock or was it user error?
