### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg'

### ISSUE THREAD

**Issue by dgleba** [pgEdge/spock#14]
I am getting the following error..
```
File "/opt/pgedge/pgedge/hub/scripts/spock.py", line 6, in <module>
docker-pgedge-n2-1  |     import util, meta, api, fire, psycopg
docker-pgedge-n2-1  | ModuleNotFoundError: No module named 'psycopg'
```
I get it on all the machines I try. This one is Xubuntu 22.04. 

I am following `https://www.pgedge.com/blog/pgedge-docker-compose-quick-start`

```
python3 -c "$(curl -fsSL https://pgedge-download.s3.amazonaws.com/REPO/install.py)"
cd pgedge/docker
docker compose build
docker compose up
```
```
albe@del-7410:/ap/test/732collection/red74/pgedge74/docker$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
albe@del-7410:/ap/test/732collection/red74/pgedge74/docker$
```

Any hints for me?

_Originally posted by @dgleba in https://github.com/pgEdge/nodectl/discussions/12#discussioncomment-7699392_

**Comment by dgleba** [comment]
I changed  `./docker/Dockerfile.el9` as follows.
```
RUN yum install python3 pip -y
RUN pip install psycopg  psycopg-binary
```
It ran without error.
Was this a good way to fix it?

**Comment by luss** [comment]
yes, thats a good way to fix.   I have since fixed it so if you were to re-install what you did wouldn't be necessary.
