### ISSUE TITLE
Slow synchronization of large amount of data

### ISSUE THREAD

**Issue by lovehxl** [pgEdge/spock#17]
Hello, when I used Spock, I tested the batch insertion of large amounts of data and found that the data was very slow year-on-year. For example, when I batch inserted 1000W data on one node, the synchronization time was very long, and it took a long time for other nodes to complete the synchronization. Is there any good way to solve the problem of slow synchronization of large amounts of data.

**Comment by wieck** [comment]
Can you be more specific about the issues you are observing?

1. What in the configuration of each node (CPU, RAM, Disk)?
2. What is the network connection's speed and latency?
3. What is the batch size in number of rows that you insert per transaction?
4. What is the average row width and what data types are involved?

**Comment by luss** [comment]
Thanks for responding Jan.  Also, are you doing a bulk load before syncronization begins or are you ding this with spock?

**Comment by lovehxl** [comment]
Firstly, the CPU is 2 * 22 and the RAM is 128GB. I am not sure about the network connection speed and latency, but it should be above 100M.


I installed a 24 node PGSQL cluster on this server and used Spock for mutual subscription between all nodes. A test table was created with UUID as the primary key, and all other field data types were text.


Then a stored procedure was created to insert data into the test table. When inserting 1000W of data at once, the synchronization of data from other nodes was slow.


-- The test table creation statement is as follows：
CREATE TABLE test1 (
 ID UUID DEFAULT gen_random_uuid ( ) PRIMARY KEY,
 a1 VARCHAR ( 200 ),
 a2 VARCHAR ( 200 ),
 a3 VARCHAR ( 200 ),
 a4 VARCHAR ( 200 ),
 a5 VARCHAR ( 200 ),
 a6 VARCHAR ( 200 ),
 a7 VARCHAR ( 200 ),
 a8 VARCHAR ( 200 ),
 a9 VARCHAR ( 200 ),
 a10 VARCHAR ( 200 ),
 a11 VARCHAR ( 200 ),
 a12 VARCHAR ( 200 ),
 a13 VARCHAR ( 200 ),
 a14 VARCHAR ( 200 ),
 a15 VARCHAR ( 200 ),
 a16 VARCHAR ( 200 ),
 a17 VARCHAR ( 200 ),
 a18 VARCHAR ( 200 ),
 a19 VARCHAR ( 200 ),
 a20 VARCHAR ( 200 ),
 a21 VARCHAR ( 200 ),
 a22 VARCHAR ( 200 ),
 a23 VARCHAR ( 200 ),
 a24 VARCHAR ( 200 )
);
-- The stored procedure is as follows：
CREATE
 OR REPLACE FUNCTION my_produce_function1 ( total INT ) RETURNS void AS $$ DECLARE
 i INTEGER := 0;
BEGIN
  WHILE
  i < total
  LOOP
  INSERT INTO test1 (a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24)
 VALUES
  ('a1-insert','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24');
 i := i + 1;
END LOOP;
END;
$$ LANGUAGE plpgsql;


-- When I execute the following statement。
select my_produce_function1(20);


| |
绿萝蔓蔓绕枝生
|
|
***@***.***
|
---- Replied Message ----
| From | Denis ***@***.***> |
| Date | 1/30/2024 22:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [pgEdge/spock] Slow synchronization of large amount of data (Issue #17) |

Thanks for responding Jan. Also, are you doing a bulk load before syncronization begins or are you ding this with spock?

**Comment by luss** [comment]
It is recommend you run with 3 or possibly 5 multi-master nodes.   Some customers are doing 7.   In a multi-master configuration all active clusters are transmitting changes to all other nodes.   24 is NOT a reasonable number for this kind of setup.   The most i've personally seen is 15, but this is 5 multi-master nodes in different regions and two semi synchronous replicas in different AZ's for each of the 5 regions.
