### ISSUE TITLE
Compilation error: ‘AttributeOpts’ has no member named ‘log_old_value’

### ISSUE THREAD

**Issue by hahnn** [pgEdge/spock#4]
Hello,

I'm trying to compile spock against a standard installation of PostgreSQL V15 (donwloaded from www.postgresql.org) on RHEL 7.

My installed PostgreSQL packages are:

postgresql15-server-15.2-1PGDG.rhel7.x86_64
postgresql15-libs-15.2-1PGDG.rhel7.x86_64
postgresql15-15.2-1PGDG.rhel7.x86_64
postgresql15-contrib-15.2-1PGDG.rhel7.x86_64
postgresql15-devel-15.2-1PGDG.rhel7.x86_64

At some point during compilation, there are errors like that:

gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -fPIC -I/usr/pgsql-15/include -I/users/nhahn/PGEDGE/spock-main/compat15 -Werror=implicit-function-declaration -I. -I./ -I/usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o spock_apply_heap.o spock_apply_heap.c
spock_apply_heap.c: In function ‘relation_has_delta_columns’:
spock_apply_heap.c:295:27: error: ‘AttributeOpts’ has no member named ‘log_old_value’
   if (aopt != NULL && aopt->log_old_value)
                           ^
spock_apply_heap.c: In function ‘build_delta_tuple’:
spock_apply_heap.c:322:28: error: ‘AttributeOpts’ has no member named ‘log_old_value’
   if (aopt == NULL || !aopt->log_old_value)
                            ^
make: *** [spock_apply_heap.o] Error 1

So, is the compilation not working against a standard community PostgreSQL V15 ?
Is it working on a patched PostgreSQL V15, if yes where is this patch available ?
On PGEDGE web site, it's clearly stated **_"Based on standard Postgres. 100% open."_** But if it needs a patched PostgreSQL, it cannot be written this is based on standard Postgres. Right ?
Do you think it may be interesting to introduce a compilation flag disabling **"Conflict-Free Delta-Apply Columns (Conflict Avoidance)"**, allowing compilation against a real standard PostgreSQL V15 and not a patched one?

Thanks for your help in my attempts to compile it and get it running using a standard PostgreSQL V15 downloaded from www.postgresql.org :-D

Best regards,
Nicolas

**Comment by hahnn** [comment]
I close this because I found the patch (I just... missed it).

**Comment by fernandomantoan** [comment]
Hello, how did you manage to patch your postgres version? Is it possible without compiling from source?
