### ISSUE TITLE
Disaster recovery and failover

### ISSUE THREAD

**Issue by nkev** [pgEdge/spock#8]
Sorry for the questions, but I think these need to be documented on your site, since I can't find any info on how Spock deals with disaster recovery and failover.

1. If a node is unavailable for an hour, say due to a hardware or major network issue, and then suddenly becomes available:
     a. Is manual intervention required on that node for it to catch up with the replication or is it all automatic?
     b. If the outage was only due to a network issue and the isolated node continued to receive writes but could not replicate for an hour, would it's writes automatically be replicated to the other nodes?

2. On a pgEdge Platform server node, if the Postgres part of pgEdge suddenly crashes but Spock is still running on the same server, does Spock automatically failover to the next closest known node so that my application layer continues working without downtime?

3. I would like to know how chatty the replication protocol between regions is. For example, if there are no writes on any server in a three region EU/US/AU setup for one hour, roughly how much data would be transmitted between the 3 regions for that hour?

Thank you!

**Comment by luss** [comment]
Greetings Nkev.    In you scenario #1 above, no intervention is required and the node that was offline will replicate it changes, and receive changes form others, when it comes back pnline.   For scenario #2, Spock runs as an extensio insiode of Postgresql.  If postgres is down, then Spock is down.   I tink you will find that the protocl is not very chatty if there is no updates going in.   each node sends a small keep alive packet every few minutes so the connections between nodes remains open.

**Comment by luss** [comment]
closed
