### ISSUE TITLE
ERROR:  schema "spock" does not exist

### ISSUE THREAD

**Issue by ernibert** [pgEdge/spock#9]
I'm trying to follow the documentation in order to get a 2-node cluster up'n'running.
After finding out that a patch has to be applied to the postgres source (i found nothing about that in the docs) pgsql ist up on both nodes and the spock extension has successfully been created on both nodes (create extension spock;).

Difficulties come up with subsequent commands. It is not that clear which one has to be executed on which node or both, so i list what i have done so far:

mlp-db-01: SELECT spock.node_create( node_name := 'provider1', dsn := 'host=mlp-db-01 port=5432 dbname=mydb' );
mlp-db-01: SELECT spock.repset_add_all_tables('default', ARRAY['public']);

mlp-db-02: SELECT spock.node_create( node_name := 'subscriber1', dsn := 'host=mlp-db-02 port=5432 dbname=mydb' );
mlp-db-02: SELECT spock.sub_create( subscription_name := 'subscription1', provider_dsn := 'host=mlp-db-01 port=5432 dbname=mydb' );
**ERROR:  could not fetch remote node info: ERROR:  schema "spock" does not exist
LINE 1: SELECT * FROM spock.node_info()**

The schema "spock" does exist on mlp-db-02 as well as on mlp-db-01 and executing the command manually returns a row (on both nodes).
```
postgres=# \dn
      List of schemas
  Name  |       Owner       
--------+-------------------
 public | pg_database_owner
 spock  | postgres
(2 rows)
``` 

The next command also failes:
mlp-db-02: SELECT spock.sub_wait_for_sync('subscription1');
**ERROR:  subscriber subscription1 not found**

Thanks in advance for any pointers to solve that!

---
PostgreSQL:  15.4
OS: Linux (Linux From Scratch, 11.3+)
Hypervisor: Both (mlp-db-01 and mlp-db-02 are VirtualBox machines)
The names mlp-db-01/2 resolve fine to IP addresses

**Comment by luss** [comment]
in your above example spock must be installed via the create extension command in your mydb database.

**Comment by ernibert** [comment]
hmm, i said 

> pgsql ist up on both nodes and the spock extension has successfully been created on both nodes (create extension spock;).

ok, maybe i'll give spock another try, maybe not.
